config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'

  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#omniauth'

  resources :entries do
    resources :entry_provisions, only: [:index, :new, :create]
  end

  resources :provisions, only: [:index, :show, :new, :create]
  resources :entry_provisions, only: [:index, :edit, :update, :destroy]
end

app/models/entry.rb
class Entry < ApplicationRecord
    validates :date, presence: true
    validates :date, uniqueness: {scope: :user_id}

    belongs_to :user
    has_many :entry_provisions, dependent: :delete_all
    has_many :provisions, through: :entry_provisions

    scope :order_by_date, -> {order(date: :desc)}
    scope :order_by_mood, -> {order(:end_of_day_mood)}
    
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
    before_action :enforce_login
    before_action :set_entry, only: [:show, :edit, :update, :destroy]
    
    def index
        @entries = Entry.order_by_date
    end
    
    def show
    end

    def new
        @entry = Entry.new(date: Date.today)
    end

    def create
        @entry = current_user.entries.build(entry_params)
        if @entry.save
            redirect_to entry_path(@entry)
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @entry.update(entry_params)
            redirect_to entry_path(@entry)
        else
            render :edit
        end
    end

    def destroy
        @entry.destroy
        redirect_to user_path(current_user)
    end

    private
        def entry_params
            params.require(:entry).permit(:date, :end_of_day_mood)
        end

        def set_entry
            @entry = Entry.find_by(id: params[:id])
        end
end

app/helpers/entries_helper.rb
module EntriesHelper
    
    def display_edit_mood_link(entry)
        if authorized_for?(entry)
            button_to "Change Mood", edit_entry_path(entry), method: :get
        end
    end
    
    def display_new_entry_provision_link(entry)
        if authorized_for?(entry)
            button_to "New Entry Provision", new_entry_entry_provision_path(entry), method: :get
        end
    end

    def display_delete_entry_link(entry)
        if authorized_for?(entry)
            button_to "Delete Entry", entry_path(entry), method: :delete
        end
    end

end

app/views/entries/_ep_edit_delete.html.erb
<% if authorized_for?(entry) %>
    <%= link_to "Edit", edit_entry_provision_path(ep) %> | <%= link_to "Delete", entry_provision_path(ep), method: :delete %>
<% end %>

app/views/entries/_form.html.erb
<% if @entry.errors.any? %>
    <div id="error_explanation">
    <h2> <%= pluralize(@entry.errors.count, "error") %> prohibited entry from being saved: </h2>
    <ul>
        <% @entry.errors.full_messages.each do |msg| %> 
            <li><%= msg %></li>
        <% end %>
    </ul>
    </div>
<% end %>

<%= form_for @entry do |f| %>
    <%= f.label :date %>: 
    <%= f.date_field :date %><br><br>
    <%= f.label :end_of_day_mood, "End of Day Mood" %>: 
    <%= f.select :end_of_day_mood, ["Elated", "Great", "Loved", "Happy", "Good", "Relaxed", "Hopeful", "Indifferent", "Sick", "Anxious", "Sad", "Bad", "Scared", "Lonely", "Disappointed"], prompt: "Select Mood" %><br><br>
    <%= f.submit %>
<% end %>

app/views/entries/edit.html.erb
<h1>Edit Entry</h1>

<%= render 'form' %>
<br><br><br>
<%= link_to "Back to Entry", entry_path(@entry) %>

app/views/entries/index.html.erb
<ul>
    <% @entries.each do |e| %>
        <li><%= link_to e.short_date, entry_path(e) %> - <%= e.user.name %> (<%= e.end_of_day_mood %>)</li>
    <% end %>
</ul>

app/views/entries/new.html.erb
<h1>New Entry</h1>
<p>Create an entry to then be able to add entry provisions to.</p>
<br>
<%= render 'form' %>

app/views/entries/show.html.erb
<h1><%= @entry.short_date %> Entry</h1>
<h3><%= link_to @entry.user.name, user_path(@entry.user) %></h3>
<h3>Mood at End of the Day: <%= @entry.end_of_day_mood %></h3> 
<%= display_edit_mood_link(@entry) %><br>
<br>
<%= display_new_entry_provision_link(@entry) %>
<br><%= display_cal_details_link(@entry) %><br><br>
<ul>
    <% @entry.entry_provisions.each do |ep| %>
        <li><%= link_to ep.provision.name, provision_path(ep.provision) %> - <%= ep.amount_and_unit %><br>
        Homemade: <%= ep.homemade ? "Yes" : "No" %><br>
        <%= ep.description %><br>
        <%= render partial: 'ep_edit_delete', locals: {entry: @entry, ep: ep} %></li><br>
    <% end %>        
</ul>

<br>
<%= display_delete_entry_link(@entry) %>