config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'

  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#omniauth'

  resources :entries do
    resources :entry_provisions, only: [:index, :new, :create]
  end

  resources :provisions, only: [:index, :show, :new, :create]
  resources :entry_provisions, only: [:index, :edit, :update, :destroy]
end

app/models/provision.rb
class Provision < ApplicationRecord
    validates :name, :provision_type, :approx_cals_per_serving, presence: true
    validates :name, uniqueness: true
    validates :approx_cals_per_serving, numericality: {greater_than: -1}

    has_many :entry_provisions
    has_many :entries, through: :entry_provisions

    scope :order_by_name, -> {order(:name)}

end

app/controllers/provisions_controller.rb
class ProvisionsController < ApplicationController
    before_action :enforce_login
    
    def index
        @provisions = Provision.order_by_name
    end

    def show
        @provision = Provision.find_by(id: params[:id])
    end

    def new
        @provision = Provision.new
    end

    def create
        @provision = Provision.new(provision_params)
        if @provision.save
            redirect_to provision_path(@provision)
        else
            render :new
        end
    end

    private
        def provision_params
            params.require(:provision).permit(:name, :provision_type, :approx_cals_per_serving)
        end
end

app/views/provisions/_provision_display.html.erb
<% if provision.entries.count != 0 %>
    <h4>Consumed on:</h4>
    <ul>
    <% provision.entries.order_by_date.each do |e| %>
        <li><%= link_to e.short_date, entry_path(e)%> by <%= e.user.name %></li><br>
    <% end %>
    </ul>
<% end %>

app/views/provisions/_provision_errors.html.erb
<% if @provision.errors.any? %>
    <div id="error_explanation">
    <h2> <%= pluralize(@provision.errors.count, "error") %> prohibited provision from being saved: </h2>
    <ul>
        <% @provision.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
    </div>
<% end %>

app/views/provisions/index.html.erb
<h1>Provisions</h1>
<ul>
<% @provisions.each do |p| %>
    <li><%= link_to p.name, provision_path(p) %> (<%= p.approx_cals_per_serving %> cals)</li>
<% end %>
</ul>
<br><br>
<%= button_to "Add Provision", new_provision_path, method: :get %>

app/views/provisions/new.html.erb
<h1>New Provision</h1>
<%= render partial: 'provision_errors', locals: {provision: @provision}  %>

<%= form_for @provision do |f| %>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br><br>
    <%= f.label :provision_type, "Provision Type" %><br>
    <%= f.select :provision_type, ["Food", "Drink"], prompt: "Select Type" %><br><br>
    <%= f.label :approx_cals_per_serving, "Approximate Calories per Serving" %><br>
    <%= f.number_field :approx_cals_per_serving, min: 0 %><br><br>
    <%= f.submit %>
<% end %>

app/views/provisions/show.html.erb
<h1><%= @provision.name %></h1>
<h3>Type: <%= @provision.provision_type %></h3>
<h3>Approximate Calories per Serving: <%= @provision.approx_cals_per_serving %> calories</h3>


<%= render partial: 'provision_display', locals: {provision: @provision} %>